live_config_reload = false

[window]
padding = { x = 0, y = 0 }
opacity = 0.85

[scrolling]
history = 20000

[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
size = 13

[colors]
[colors.primary]
background = "#000000"

[env]
term = "xterm-256color"
